// <auto-generated />
using System;
using AvanceradDotNetLabb4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvanceradDotNetLabb4.Migrations
{
    [DbContext(typeof(ThisDbContext))]
    [Migration("20230420134354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.InterestPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FkInterestId")
                        .HasColumnType("int");

                    b.Property<int?>("FkPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkInterestId");

                    b.HasIndex("FkPersonId");

                    b.ToTable("InterestsPersons");
                });

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FkInterestPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkInterestPersonId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.InterestPerson", b =>
                {
                    b.HasOne("AvanceradDotNetLabb4.Models.Interest", "FkInterest")
                        .WithMany()
                        .HasForeignKey("FkInterestId");

                    b.HasOne("AvanceradDotNetLabb4.Models.Person", "FkPerson")
                        .WithMany()
                        .HasForeignKey("FkPersonId");

                    b.Navigation("FkInterest");

                    b.Navigation("FkPerson");
                });

            modelBuilder.Entity("AvanceradDotNetLabb4.Models.Link", b =>
                {
                    b.HasOne("AvanceradDotNetLabb4.Models.InterestPerson", "FkInterestPerson")
                        .WithMany()
                        .HasForeignKey("FkInterestPersonId");

                    b.Navigation("FkInterestPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
